linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gofmt
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
