version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gocritic
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - io.Copy
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (io.Closer).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close
        - (*github.com/jmoiron/sqlx.DB).Close
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
