# goreleaser release --clean --release-notes release_notes.md --verbose
# goreleaser release --snapshot --clean --skip homebrew --verbose
# goreleaser release --snapshot --clean --skip homebrew,docker

version: 2

# Don't use a FG Pat here. Use Classic PAT b/c ghcr complains about permissions.
env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - sh -c "cd ui && bun install --frozen-lockfile"
    - sh -c "cd ui && bun run build"
    - sh -c "rm -rf internal/ui/dist/assets && cp -r ui/dist/* internal/ui/dist/"

builds:
  # Linux builds
  - id: fdsn
    binary: fdsn
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # macOS builds (amd64 + arm64 for true universal binary)
  - id: fdsn-macos
    binary: fdsn
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # Windows builds
  - id: fdsn-windows
    binary: fdsn
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# macOS universal binary with code signing and notarization
universal_binaries:
  - id: fdsn-macos
    replace: true
    hooks:
      post: /Users/joescharf/.local/bin/pycodesign.py fdsn_pycodesign.ini -O {{ .Version }}

archives:
  - id: fdsn-linux-archive
    ids:
      - fdsn
    formats:
      - tar.gz
    files:
      - README.md

  # macOS archive: zip with binary only (what Homebrew expects)
  - id: fdsn-macos-archive
    ids:
      - fdsn-macos
    formats:
      - zip
    files:
      - none*

  - id: fdsn-windows-archive
    ids:
      - fdsn-windows
    formats:
      - zip
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: joescharf
    name: fdsn
  ids:
    - fdsn-linux-archive
    - fdsn-macos-archive
    - fdsn-windows-archive
  extra_files:
    - glob: ./dist/fdsn_macos_universal.pkg
  draft: true
  replace_existing_draft: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

# brew install joescharf/tap/fdsn
homebrew_casks:
  - name: fdsn
    ids:
      - fdsn-macos-archive
    binaries:
      - fdsn
    repository:
      owner: joescharf
      name: homebrew-tap
    directory: Casks
    skip_upload: auto
    commit_author:
      name: releaserbot
      email: joe@joescharf.com
    homepage: https://github.com/joescharf/fdsn
    description: "Seismic station metadata management -- import, explore, and re-serve FDSN data from a single binary."

dockers_v2:
  - images:
      - "ghcr.io/joescharf/fdsn"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
