# goreleaser release --clean --release-notes release_notes.md --verbose
# goreleaser release --snapshot --clean --skip homebrew --verbose
# goreleaser release --snapshot --clean --skip homebrew,docker

version: 2

# Don't use a FG Pat here. Use Classic PAT b/c ghcr complains about permissions.
env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - sh -c "cd ui && bun install --frozen-lockfile"
    - sh -c "cd ui && bun run build"
    - sh -c "rm -rf internal/ui/dist/assets && cp -r ui/dist/* internal/ui/dist/"

builds:
  # Linux builds
  - id: fdsn
    binary: fdsn
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  # macOS builds (amd64 + arm64 for true universal binary)
  - id: fdsn-macos
    binary: fdsn
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  # Windows builds
  - id: fdsn-windows
    binary: fdsn
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

# macOS universal binary with code signing and notarization
universal_binaries:
  - id: fdsn-macos
    replace: true
    hooks:
      post: uv run /Users/joescharf/.local/bin/pycodesign.py fdsn_pycodesign.ini -O {{ .Version }}

archives:
  - id: fdsn-linux-archive
    ids:
      - fdsn
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else }}{{ .Arch }}{{ end }}"
    files:
      - README.md

  # macOS archive: zip for Homebrew
  - id: fdsn-macos-archive
    ids:
      - fdsn-macos
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else if eq .Arch \"all\" }}universal{{ else }}{{ .Arch }}{{ end }}"
    files:
      - README.md

  - id: fdsn-windows-archive
    ids:
      - fdsn-windows
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else }}{{ .Arch }}{{ end }}"
    files:
      - README.md

signs:
  - id: notarize-macos-zip
    cmd: sh
    args:
      - -c
      - 'xcrun notarytool submit "${artifact}" --keychain-profile SCHARFNADO_LLC --wait && touch "${signature}"'
    artifacts: archive
    ids:
      - fdsn-macos-archive
    signature: "${artifact}.notarized"
    output: true

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: joescharf
    name: fdsn
  ids:
    - fdsn-linux-archive
    - fdsn-macos-archive
    - fdsn-windows-archive
  extra_files:
    - glob: ./dist/fdsn_macos_universal.pkg
  draft: false
  prerelease: auto

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

# brew install joescharf/tap/fdsn
homebrew_casks:
  - name: fdsn
    ids:
      - fdsn-macos-archive
    binaries:
      - fdsn
    repository:
      owner: joescharf
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    skip_upload: auto
    commit_author:
      name: releaserbot
      email: joe@joescharf.com
    homepage: https://github.com/joescharf/fdsn
    description: "Seismic station metadata management -- import, explore, and re-serve FDSN data from a single binary."

dockers_v2:
  - images:
      - "ghcr.io/joescharf/fdsn"
    tags:
      - "v{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
